@echo off
set POSTGRES_USERNAME=postgres
set POSTGRES_PASSWORD=root123456
set POSTGRES_HOST=database-1.cbcof6lyijp3.us-east-1.rds.amazonaws.com
set POSTGRES_DB=postgres
set AWS_BUCKET=arn:aws:s3:::unique97-75139724085
set AWS_REGION=us-east-1
set AWS_PROFILE=default
set JWT_SECRET=mysecretstring
set URL=http://localhost:8100